In [1]:
import sys

sys.path.append("../src")

In [2]:
from tsdataloader import PostgresDataLoader, PostgresDataset

/root/projects/tsdataloader/.venv/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


# Setup postgres

## Docker command
```docker
docker run -d 
    --name postgres 
    -e POSTGRES_DB=your_dbname 
    -e POSTGRES_USER=your_user 
    -e POSTGRES_PASSWORD=your_password 
    -p 5432:5432 
    postgres

docker exec -it postgres /bin/bash
>>> psql --dbname=your_dbname --username=your_user
```

```sql
your_dbname=#
CREATE TABLE IF NOT EXISTS my_table (
    v1 FLOAT,
    v2 FLOAT
);

your_dbname=#
INSERT INTO my_table (v1, v2)
SELECT random(), random()
FROM generate_series(1, 100);

your_dbname=#
SELECT COUNT(*) FROM my_table;
```

In [3]:
dataset = PostgresDataset(
    db="your_dbname",
    user="your_user",
    password="your_password",
    host="host.docker.internal",
    port="5432",
    query="SELECT v1,v2 FROM my_table;",
    fetch_size=10000,
)

In [4]:
import torch

dataloader = PostgresDataLoader(dataset, batch_size=5, dtype=torch.float32)

for batch in dataloader:
    print(batch)

tensor([[0.3642, 0.4362],
        [0.4080, 0.3847],
        [0.2716, 0.9373],
        [0.4719, 0.7099],
        [0.3831, 0.1706]])
tensor([[0.9456, 0.7972],
        [0.6847, 0.5980],
        [0.2215, 0.2913],
        [0.3048, 0.9703],
        [0.3780, 0.7710]])
tensor([[0.6752, 0.9038],
        [0.4610, 0.7928],
        [0.1848, 0.5278],
        [0.7699, 0.4269],
        [0.0374, 0.2666]])
tensor([[0.2119, 0.6777],
        [0.0557, 0.7100],
        [0.1120, 0.1999],
        [0.7582, 0.2853],
        [0.0725, 0.0597]])
tensor([[0.3126, 0.8715],
        [0.2621, 0.0571],
        [0.0225, 0.3963],
        [0.1746, 0.5025],
        [0.4786, 0.4282]])
tensor([[0.6012, 0.0446],
        [0.7433, 0.5118],
        [0.2731, 0.9571],
        [0.1689, 0.7854],
        [0.2222, 0.8590]])
tensor([[0.6349, 0.4556],
        [0.0195, 0.9814],
        [0.2151, 0.6351],
        [0.0930, 0.8774],
        [0.2824, 0.5820]])
tensor([[0.5528, 0.5149],
        [0.7535, 0.8194],
        [0.0803, 0.7185],
     

/root/projects/tsdataloader/src/tsdataloader/dataloader.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  yield torch.stack([torch.tensor(item) for item in batch]).type(self.dtype).T


In [4]:
import torch

dataloader = PostgresDataLoader(dataset, batch_size=5, dtype=torch.float32)

for batch in dataloader:
    print(batch)

tensor([[0.3642, 0.4362],
        [0.4080, 0.3847],
        [0.2716, 0.9373],
        [0.4719, 0.7099],
        [0.3831, 0.1706]])
tensor([[0.9456, 0.7972],
        [0.6847, 0.5980],
        [0.2215, 0.2913],
        [0.3048, 0.9703],
        [0.3780, 0.7710]])
tensor([[0.6752, 0.9038],
        [0.4610, 0.7928],
        [0.1848, 0.5278],
        [0.7699, 0.4269],
        [0.0374, 0.2666]])
tensor([[0.2119, 0.6777],
        [0.0557, 0.7100],
        [0.1120, 0.1999],
        [0.7582, 0.2853],
        [0.0725, 0.0597]])
tensor([[0.3126, 0.8715],
        [0.2621, 0.0571],
        [0.0225, 0.3963],
        [0.1746, 0.5025],
        [0.4786, 0.4282]])
tensor([[0.6012, 0.0446],
        [0.7433, 0.5118],
        [0.2731, 0.9571],
        [0.1689, 0.7854],
        [0.2222, 0.8590]])
tensor([[0.6349, 0.4556],
        [0.0195, 0.9814],
        [0.2151, 0.6351],
        [0.0930, 0.8774],
        [0.2824, 0.5820]])
tensor([[0.5528, 0.5149],
        [0.7535, 0.8194],
        [0.0803, 0.7185],
     